#!/usr/bin/env python3
"""Rebuild the installable theme package in drafts/theme/ from the sources.

Every draft page loads this package, so when it is not regenerated the drafts
keep serving defects already fixed in design-system/. It had drifted to
brand-link #0074B7 (4.41:1 on brand-soft), status-info #0074B7, no Arabic
--font-sans rebinding and no --mt-target-icon: Arabic in Helvetica and touch
targets under 44px, on every draft.

Run this after any change to tokens.json or components/bundle.css.
"""
import json, pathlib, shutil
ROOT = pathlib.Path(__file__).resolve().parents[2]
DS   = ROOT/'design-system'
OUT  = ROOT/'drafts/theme'
t = json.loads((DS/'tokens.json').read_text())

# --- tokens.css: the install variant - values only, no usage prose, and the
#     subset woff2 that ships beside it rather than the full variable TTF.
L = ['/* MIDTRANS theme — generated by tools/audit/gen_theme_package.py.',
     '   Do not edit by hand: edit design-system/tokens.json and re-run it. */']
def block(sel, theme, ind='  '):
    L.append(sel + ' {')
    for c in t['color']['tokens']:  L.append(f"{ind}--{c['name']}: {c['value'][theme]};")
    for s in t['shadow']['tokens']: L.append(f"{ind}--{s['name']}: {s['value'][theme]};")
    L.append('}')
block(':root, [data-theme="light"]', 'light')
block('[data-theme="dark"]', 'dark')
L.append('@media (prefers-color-scheme: dark) {')
L.append('  :root:not([data-theme="light"]) {')
for c in t['color']['tokens']:  L.append(f"    --{c['name']}: {c['value']['dark']};")
for s in t['shadow']['tokens']: L.append(f"    --{s['name']}: {s['value']['dark']};")
L.append('  }')
L.append('}')
L.append(':root {')
for s in t['spacing']['tokens']: L.append(f"  --{s['name']}: {s['value']};")
for s in t['radius']['tokens']:  L.append(f"  --{s['name']}: {s['value']};")
fam = t['type']['families']
L.append(f"  --font-sans: {fam['sans']};")
L.append(f"  --font-arabic: {fam['arabic']};")
L.append(f"  --font-mono: {fam['mono']};")
VAR = {'sans': '--font-sans', 'arabic': '--font-arabic', 'mono': '--font-mono'}
for g in t['type']['groups']:
    for st in g['styles']:
        v = VAR[st.get('family') or g['family']]
        L.append(f"  --text-{st['name']}: {st['fontWeight']} {st['fontSize']}/{st['lineHeight']} var({v});")
L.append('}')
# paper is white whatever the screen was set to
L.append('@media print {')
L.append('  :root, [data-theme="light"], [data-theme="dark"] {')
for c in t['color']['tokens']:  L.append(f"    --{c['name']}: {c['value']['light']};")
for s in t['shadow']['tokens']: L.append(f"    --{s['name']}: none;")
L.append('  }')
L.append('}')
for g in t['type']['groups']:
    for st in g['styles']:
        v = VAR[st.get('family') or g['family']]
        L.append(f".{st['name']} {{ font-family: var({v}); font-size: {st['fontSize']}; "
                 f"line-height: {st['lineHeight']}; font-weight: {st['fontWeight']}; "
                 f"letter-spacing: {st.get('letterSpacing') or '0'}; }}")
L += ['@font-face {', '  font-family: "Cairo";',
      '  src: url("fonts/cairo.woff2") format("woff2");',
      '  font-weight: 200 1000;', '  font-style: normal;',
      '  font-display: swap;', '}']
(OUT/'tokens.css').write_text('\n'.join(L) + '\n')

# --- midtrans.css: the component stylesheet, verbatim.
shutil.copyfile(DS/'components/bundle.css', OUT/'midtrans.css')

print(f"tokens.css   {(OUT/'tokens.css').stat().st_size:,} bytes")
print(f"midtrans.css {(OUT/'midtrans.css').stat().st_size:,} bytes")
